"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SMTP_SERVICE = exports.SMTP_HOST_NAME = exports.GMAIL_PASSWORD = exports.GMAIL_USER = exports.BRIGHT_DATA_PASSWORD = exports.BRIGHT_DATA_USERNAME = exports.JWT_REFRESH_SECRET = exports.JWT_SECRET = exports.MONGODB_URI = exports.PORT = void 0;
exports.PORT = process.env.PORT;
exports.MONGODB_URI = process.env.MONGODB_URI;
exports.JWT_SECRET = process.env.JWT_SECRET;
exports.JWT_REFRESH_SECRET = process.env.JWT_REFRESH_SECRET;
exports.BRIGHT_DATA_USERNAME = process.env.BRIGHT_DATA_USERNAME;
exports.BRIGHT_DATA_PASSWORD = process.env.BRIGHT_DATA_PASSWORD;
exports.GMAIL_USER = process.env.GMAIL_USER;
exports.GMAIL_PASSWORD = process.env.GMAIL_PASSWORD;
exports.SMTP_HOST_NAME = process.env.SMTP_HOST_NAME;
exports.SMTP_SERVICE = process.env.SMTP_SERVICE;
